### ISSUE TITLE
Prototype 1.1 release checklist

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/SQAaaS#24]
### Landing page
  * [x] Shall include a i) general description, ii) definition of _CI/CD_ and _digital badges_, iii) intro to Pipeline as a Service, iv) intro to Quality Assessment & Awarding, v) deploy your own SQAaaS 

### Pipeline as a Service block 
  * [x] Follows a 4 steps workflow: i) The Repos (_find sth more appropriate_), ii) The Services, iii) The Criteria, iv) The Pipeline

### The Repos panel
  * [x] Make clear distinction (through the web) between the so-called _pipeline repo_ (the target repo where the pipeline will be added) and _additional repos_
  * [x] Using a _pipeline repo_ is the default behavior
  * [x] The definition of external repositories appears only upon user selection (_Does the pipeline requires to checkout external repositories?_ checklist)
    * [x] Allows to add a specific branch name
    * [x] Remove _Pipeline react to al changes?_ checkbox, no longer needed

### The Services panel
  * The Docker push panel should contain:
    * [x] Appear outside of the advanced features panel, in a e.g _Would you like to push the Docker image to a registry?_ checkbox
    * [x] Require mandatory Docker image build parameters: _'Dockerfile', 'image name', 'context'(?)_
    * [ ] Information icon for 'Dockerfile' input field, **stating that the value is the relative path (from the root path of the repository) to the Dockerfile, including the file name of the latter** (not only the folder path) 
    * [x] Warning that a Jenkins credential might be needed for a successful push
    * [ ] Inform about the specifics of using a Github id for signing into Jenkins
    * [ ] Inform about the possibility to push to `eoscsynergyapps` Docker Hub repository (if the user does not want to create a credential in Jenkins)
    * [ ] When using generic credentials, the web should parse the 'image name' value (as it is being written) & add the resultant Docker registry repo underneath the input field.
    * [ ] The 'Image name' input fields must have a '?' icon with the information about the possibility of using defined env  & git-related. This message is currently displayed in a info panel
    * [ ] Review that Credentials can be created in Jenkins by developers of Thematic Services
    * [x] "+ ADD CRITERIA" to "+ ADD CRITERION"
    * [x] When clicking on "+ ADD CRITERIA" button without adding any builder, a Warning panel shall pop up to inform that "Please add a builder tool to finish off the criterion definition"

### The Criteria panel
  * [x] Service dropdown list shall appear first 
  * [x] Default repo is the 'this_repo' one. If any external repo has been defined, a new dropdown list shall appear with the external repo selection. This dropdown is introduced by _"Does the criterion apply to an outside repo?"_ checklist
  * [x] The **'Choose a Criteria' dropdown shall appear centered in the panel**, and shall be the **unique form being displayed the first time** we access this panel. The rest of forms will appear upon the criterion selection, including the 'Builder tool'. The 'Builder settings' text shall be moved to a tooltip ('?' icon) next to the 'Choose a builder tool' form
  * [x] Both `tox_file` and `testenv` shall be optional. The API takes care of setting defaults.

### The Pipeline panel
* Shall include:
  * [x] an i) Information summary, ii) JePL file contents arranged in tabs, iii) Actions through buttons (download zip, pull request and try out pipeline)
* JePL content files
  * [x] Display the scripts generated (if any) for the `commands` builder (see https://github.com/EOSC-synergy/sqaaas-web/issues/82)
* Pull request
  * [x] Add an input field for the branch when creating PRs (see https://github.com/EOSC-synergy/sqaaas-web/issues/81)
* Try out pipeline 
  * [x] When running the pipeline (Try out pipeline), a progress bar (or similar) shall be displayed
  * [x] When running the pipeline (Try out pipeline), the navigation shall be blocked until it gets a status value from the API
  * [x] When running the pipeline (Try out pipeline), a _Cancel execution_ button will be available, but only enabled after a status value is obtained from the API
  * [x] The loading spinner must display the status of the Jenkins job (as returned by the API)
  * [x] The label for the URL could be instead of just 'URL' sth like _'URL of the pipeline's target repository'_
* The Error info panel
  * [x] An unexpected error is currently reported with no text. We shall put some message there such as _"Unexpected error obtained from the SQAaaS API"_
  * [x] When running the pipeline and a 'this_repo' has been defined, the Error info panel is displayed (prompting for a source repo to checkout). We shall use Warning info panel instead (with different color), as it is not an error.
  * [x] When prompting for a `repo_url` (and `repo_branch`), add an info note (bell) that indicates that repositories MUST be public for the checkout to work
* Displaying the results
  * [ ] If any Docker image has been pushed to an external registry, highlight this in the view by adding a link to the registry's image URL
  * [x] The badge shall be centered
  * [ ] Could the 'Full Stage View' provided by Jenkins be embedded as well into the results, somewhere around the badge (e.g. https://jenkins.eosc-synergy.eu/job/eosc-synergy-org/job/my_pipeline.sqaaas/job/main/workflow-stage/)

### General aspects from the panels  
* [x] Preserve the setup when moving back and forth between panels (see https://github.com/EOSC-synergy/sqaaas-web/issues/76)
* [x] Do not remove unrelated components: for instance, when removing a service, do not remove repositories not related to that one. Likewise, if they are related, and thus they need to be removed, add a Warning info panel saying that _"By removing service X, you will remove all the associated .."_
* [x] All the key:value forms must have both 'key' and 'value' lowercase, so that the don't appear as important as the parent title
* [ ] Checkbox questions (yes/no answer) in a different color. Should not be blue, since this is the color of the links.
* [ ] The '?' tooltip for the 'Jenkins Credential ID' must have the explicit link to https://jenkins.eosc-synergy.eu, and any additional (brief) explanation of how to add credentials there.

### Bugs
* [x] Double-encode branch names before being passed to Jenkins
* [x] External repos are not added to `config:project_repos`
* [x] Even when pipeline is in SUCCESS status, the run pipeline popup keeps checking for the status
* [x] Docker push is always passed as true (see https://github.com/EOSC-synergy/sqaaas-web/issues/77)
* [x] Tox builder properties are not correctly set up in the JSON payload (see https://github.com/EOSC-synergy/sqaaas-web/issues/83)
* [x] When an error response `4xx`occurs, the web is not showing the message returned by the API (see https://github.com/EOSC-synergy/sqaaas-web/issues/85)

### Basic operation
* run_pipeline()
  * No query parameters: 
    * [x] GH repo _does not exist_ & repo's job _exists_ in Jenkins
    * [x] GH repo _does not exist_ & repo's job _does not exist_ in Jenkins
    * [x] GH repo _exists_ & repo's job _exists_ in Jenkins
  * Using query parameters (`issue_badge`, `repo_url`, `repo_branch`):
    * `repo_url` in the same GH org
      * [ ] `repo_url` NOT exists
      * [x] `repo_url` exists
      * [ ] `repo_url` and `repo_branch` exists (is branch updated?)
    * `repo_url` not in the same GH org
      * [ ] `repo_url` NOT exists
      * [ ] `repo_url` exists
      * [ ] `repo_url` and `repo_branch` exists (is branch updated?)
      * [ ]  `repo_url` NOT contains '.git' extension (github.com & gitlab.com)
    * Providing invalid values:
      * [ ] `repo_url` does not exist (github.com & gitlab.com)
      * [x] `repo_branch` does not exist (github.com & gitlab.com)
      * [ ] `repo_url` contains '.git' extension (github.com & gitlab.com)
      * [ ] `repo_url` is private (github.com & gitlab.com)
 * update_pipeline()
   * [x] Update pipeline & run_pipeline()
   * [x] Update `commands` builder & run_pipeline()
   * [x] Update pipeline & run_pipeline() & reuse JePL config files (Jenkinsfile, config.yml, docker-compose.yml)
   * [ ] Update pipeline & run_pipeline() & reuse multiple config.yml files (`when` condition)
   * [x] Update pipeline's `commands` builder & run_pipeline() & handle resultant scripts
   * [x] Update multiple pipeline's `commands` builder & run_pipeline() & handle resultant scripts
 * status()
   * [x] WAITING_SCAN_ORG if triggered scan_org in Jenkins
   * [x] NOT_EXECUTED if job not queued in Jenkins
   * [x] QUEUED if job queued in Jenkins, but not started
   * [x] EXECUTING if job started
   * [x] SUCCESS if pipeline ended successfully
   * [x] FAILURE if pipeline failed
* pull_request()
  * [x] target: external repo & origin: not present (not triggered run_pipeline())
  * [x] target: external repo & origin: present (shall update pull request if already exists)
  * [x] target: repo within GH's eosc-synergy org & origin: not present (not triggered run_pipeline())
  * [x] target: repo within GH's eosc-synergy org & origin: present (shall create a new PR with random name for the branch)
  * [x] Returns `4xx` error when the target repository and/or branch does not exist

#### `when` clause
  * [x] Able to compose it through advanced features in the web
  * [x] Generate the appropriate set of `config.yml` files
  * [x] Create an individual stage in the `Jenkinsfile` that maps the appropriate (criterion, `config.yml` file) data
  * [x] Remove the unnecessary `config.yml` files whenever the pipeline repo is updated
#### Docker push feature
* Requirements
  * [x] Enabled when composer's image has `push: true`
  * [x] `credential_id` is set by the user OR user selects (checkbox) the catch-all 'eoscsynergybot' credential id
  * [x] Build parameters: combination of `Dockerfile` or `context`
* Manage context for `Dockerfile` parameter
  * [x] Automatically setting `context` for the user, both with 'this_repo' and external repos
* Credentials are required to push Docker images to registries. There are two way to accomplish that:
  * [x] Using custom user credentials created by such user via Jenkins interface (need to log into Jenkins)
  * [x] Using a catch-all credential that only pushes to `eoscsynergyapps` organization in Docker Hub.
  * [x] The API automatically sets the Docker environment variables: `JPL_DOCKERPUSH`, `JPL_USERNAME`, `JPL_PASSWORD`
####  The `commands` builder
  * [x] Automatically handle the chdir operation
  * [x] Applicable only in the case that the criterion has defined a repository. Otherwise (when `this_repo`) do nothing
  * [x] By means of creating scripts inside `.sqa` folder and run them with `/usr/bin/env sh <script.sh>`
  * [x] Remove the unnecessary script files whenever the pipeline repo is updated
#### The Tox builder
  * [x] Allows to both use `tox` and `commands`
  * [x]  Automatically handle the chdir operation
  * [x] Handle `tox_file` path automatically for the user (it is now required by the jpl-validator)
#### Badge issuing
  * [x] The Pipeline as a Service module will temporarily generate and display a badge after the successful execution of the pipeline
  * [x] The badge will be displayed in Step 4 (The Pipeline), at the bottom of the panel

#### Run pipeline
* [x] this_repo + `repo_branch` NOT IN `repo_url` (fails with "409 Client Error: Conflict for url: https://jenkins.eosc-synergy.eu/job/eosc-synergy-org/job/my_pipeline.sqaaas/job/master/build")
#### Pull request & Run pipeline
* [ ] Pull request after Run pipeline
* [ ] Run pipeline after Pull request

**Comment by orviz** [comment]
Released
